[package]
name = "s2v"
version = "0.7.0"
edition = "2021"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]
anyhow = "1.0.82"

clap = "4.5.4"

log = "0.4.21"
log4rs = "1.3.0"