apiVersion: v1
data:
{{ secretsBlock }}
kind: Secret
metadata:
  annotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.vault.svc:8200
    vault.security.banzaicloud.io/vault-role: {{ serviceName }}
  name: {{ serviceName }}
  namespace: {{ namespace }}
type: Opaque