apiVersion: v1
data:
  BAD_UTF8_VALUE: d6320dcf844b2b13561b47c647d6076c
kind: Secret
metadata:
  annotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.vault.svc:8200
    vault.security.banzaicloud.io/vault-role: app.company.com
  name: app-secret
  namespace: demo
type: Opaque