apiVersion: v1
data:
  DATABASE_URL: YXBwLmRi
  DATABASE_USER: ZGVtby1hcHAtdXNlcg==
  DATABASE_PASSWORD: MTAyOWowOXFlbERBbQ==
  TOKEN: non-encoded-value
kind: Secret
metadata:
  annotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.vault.svc:8200
    vault.security.banzaicloud.io/vault-role: app.company.com
  name: app-secret
  namespace: demo
type: Opaque